### ISSUE TITLE
target

### ISSUE THREAD

**Issue by NotPhelps** [Sober881/qb-vendingjob#1]
i dont seem to get the ability to target it shows but doesnt allow me to click on it

**Comment by Sober881** [comment]
If you do not use qb-target you will need to write the function for your target in place of qb-target things

**Comment by NotPhelps** [comment]
so yeha i use qb-target when i go to the ped and click on it  nothing happen other then the menu comes up and freezes untill you walk away so im not sure why

**Comment by NotPhelps** [comment]
https://prnt.sc/T9Xicg5CN8pE
